scripts:
  lint:
    - husky run pre-commit
    - husky run commit-msg
  test:
    - go test -v -race ./...
  cover:
    - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  install:
    - go install github.com/go-courier/husky

hooks:
  pre-commit:
    - go vet ./...
    - husky lint-staged
  commit-msg:
    - husky lint-commit

lint-staged:
  "*.go":
    - gofmt -l -w

lint-commit:
  email: "^(.+@gmail.com|.+@qq.com)$"